services:

  i2b2-webclient:
    image: i2b2/i2b2-webclient:${I2B2_WEBCLIENT_TAG}
    container_name: i2b2-webclient

    restart: unless-stopped
    ports:
      - "80:80"
      - "444:443"
    command: /run-httpd.sh localhost
    volumes:
      - ../assets/recover.png:/var/www/html/webclient/assets/images/logo.png
      - ../assets/login.html:/var/www/html/webclient//js-i2b2/cells/PM/assets/login.html
      - ../assets/main_display.html:/var/www/html/webclient/assets/main_display.html

    depends_on:
      - i2b2-core-server
    networks:
      - i2b2-net

  i2b2-core-server:
    image: i2b2/i2b2-core-server:${I2B2_CORE_SERVER_TAG}
    container_name: i2b2-core-server
    restart: unless-stopped
    environment:

      - DS_TYPE=${I2B2_DS_TYPE}
      - DS_PORT=${I2B2_DS_PORT}
      - DS_IP=${I2B2_DS_IP}
      - DS_SERVICE_NAME=${I2B2_DS_SERVICE_NAME}

      - DS_CRC_IP=${I2B2_DS_CRC_IP}
      - DS_CRC_PORT=${I2B2_DS_CRC_PORT}
      - DS_CRC_USER=${I2B2_DS_CRC_USER}
      - DS_CRC_PASS=${I2B2_DS_CRC_PASS}

      - DS_ONT_IP=${I2B2_DS_ONT_IP}
      - DS_ONT_PORT=${I2B2_DS_ONT_PORT}
      - DS_ONT_USER=${I2B2_DS_ONT_USER}
      - DS_ONT_PASS=${I2B2_DS_ONT_PASS}

      - DS_PM_IP=${I2B2_DS_PM_IP}
      - DS_PM_PORT=${I2B2_DS_PM_PORT}
      - DS_PM_USER=${I2B2_DS_PM_USER}
      - DS_PM_PASS=${I2B2_DS_PM_PASS}

      - DS_HIVE_IP=${I2B2_DS_HIVE_IP}
      - DS_HIVE_PORT=${I2B2_DS_HIVE_PORT}
      - DS_HIVE_USER=${I2B2_DS_HIVE_USER}
      - DS_HIVE_PASS=${I2B2_DS_HIVE_PASS}

      - DS_WD_IP=${I2B2_DS_WD_IP}
      - DS_WD_PORT=${I2B2_DS_WD_PORT}
      - DS_WD_USER=${I2B2_DS_WD_USER}
      - DS_WD_PASS=${I2B2_DS_WD_PASS}
    # volumes:
    #   - ./custom_datasource.txt:/opt/jboss/wildfly/customization/custom_datasource.txt
    networks:
      - i2b2-net
    depends_on:
      - i2b2-data-oracle

  i2b2-data-oracle:
    image: i2b2/i2b2-data-oracle:${I2B2_DATA_ORACLE_TAG}
    container_name: i2b2-data-oracle

    environment:
      - ORACLE_PWD=${I2B2_ORACLE_PASS}
    networks:
      - i2b2-net
    # ports:
    #   - "1521:1521"
    #   - "5500:5500"
networks:
  i2b2-net:
    name: i2b2-net
    driver: bridge
